### ISSUE TITLE
Error: Mapped port can only be obtained after the container is started

### ISSUE THREAD

**Issue by bytekast** [testcontainers/testcontainers-spock#23]
When running the sample DatabaseTest from the docs, the following error occurs:

```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
```

**Comment by kiview** [comment]
Just tried out the example, works on my machine and the `PostgresContainerIT` test class is basically the same and part of the CI pipeline.
Can you share your example project?

**Comment by bytekast** [comment]
actually i was able to get around it by adding @ClassRule to the shared container. thanks!

**Comment by kiview** [comment]
That should not be needed and in this case the testcontainers-spock and testcontainers-java implementation might actually clash ;)
Having `@Testcontainers` annotation and a `@Shared` annotation should have the same effect as having the JUnit `@Classrule` annotation.

I would still be interested in a non working code example / project :)

**Comment by bytekast** [comment]
i can try to recreate it in a blank project and send it over
