### ISSUE TITLE
TestContainers?

### ISSUE THREAD

**Issue by bsideup** [testcontainers/testcontainers-spock#5]
Hi! 

I see that you were inspired by https://github.com/FaustXVI/junit5-docker

We develop a library called TestContainers ( https://github.com/testcontainers/testcontainers-java ). It's mature, flexible and powerful engine to use Docker in your integration tests.

As the developer of junit5-docker already agreed to join the forces ( https://github.com/FaustXVI/junit5-docker/issues/91 ), probably you will want to join us as well :)

We would really love to see some Spock/Groovy-native bindings for TestContainers, and it sounds like a great opportunity for you - to focus on it, instead of having to deal with the environment detection, container management, cleanups, etc...

WDYT?

Join our Slack anyway:
http://slack.testcontainers.org

**Comment by kiview** [comment]
When I started this project, I only knew about https://github.com/FaustXVI/junit5-docker and I wanted to have something simillar for Spock. So I simply did not know about [TestContainers](https://github.com/testcontainers/testcontainers-java).

I'll definitely look into this and love to join efforts :)
