### ISSUE TITLE
Provide container handles for test code

### ISSUE THREAD

**Issue by Faradax** [testcontainers/testcontainers-spock#6]
I would like to be able to control - and gain information about - the spawned containers from inside the test. Here are two examples where that could be handy.

* For doing things such as recovery-tests or similar, where I would simulate a failure of collaborating systems, I could stop (and later restart) a container from within the test.
* For accessing the container independently of the docker setup (dind / wormhole / native), I could look up the containers IP from the handle.

There may be many other examples, of course...

**Comment by kiview** [comment]
Thanks to #7 accessing the ip is now possible. It's also possible to start and stop a container using the injected `DockerClientFacade`. However, this will currently delete the container when stopping it.

It might be be useful to have methods like `pause()` and `resume()`?

**Comment by Faradax** [comment]
I would recommend **not** deviating from the naming convention of the CLI too much. removing a container is "docker rm", while "docker stop" leaves the container intact so that it can be restarted with "docker start". "docker pause" from the CLI stops the processing inside the container (which is undone by "docker unpause").
